### ISSUE TITLE
Having problem to install the package 

### ISSUE THREAD

**Issue by khojandin** [YosefLab/VISION#124]
I'm trying to install the package (using RStudio) but getting this error. 
Downloading GitHub repo YosefLab/VISION@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: httpuv (1.6.9 -> 1.6.10) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
httpuv (1.6.9 -> 1.6.10) [CRAN]
Installing 1 packages: httpuv

  There is a binary version available but the source version is later:
       binary source needs_compilation
httpuv  1.6.9 1.6.10              TRUE

installing the source package ‘httpuv’

trying URL 'https://cran.rstudio.com/src/contrib/httpuv_1.6.10.tar.gz'
Content type 'application/x-gzip' length 1875497 bytes (1.8 MB)
downloaded 1.8 MB

* installing *source* package 'httpuv' ...
** package 'httpuv' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/NiloufarKhojandi/AppData/Local/Programs/R/R-4.3.0/library/httpuv'
* restoring previous 'C:/Users/NiloufarKhojandi/AppData/Local/Programs/R/R-4.3.0/library/httpuv'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\NiloufarKhojandi\AppData\Local\Programs\R\R-4.3.0\library\00LOCK-httpuv\httpuv\libs\x64\httpuv.dll to C:\Users\NiloufarKhojandi\AppData\Local\Programs\R\R-4.3.0\library\httpuv\libs\x64\httpuv.dll: Permission denied

The downloaded source packages are in
	

‘C:\Users\NiloufarKhojandi\AppData\Local\Temp\RtmpGm7dIC\downloaded_packages’
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\NiloufarKhojandi\AppData\Local\Temp\RtmpGm7dIC\remotesa77c10e27c12\YosefLab-VISION-8dc5c4e/DESCRIPTION' ...
─  preparing 'VISION': (3.7s)
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory 'VISION/vignettes/web_only'
   Omitted 'LazyData' from DESCRIPTION
─  building 'VISION_3.0.1.tar.gz'
   
* installing *source* package 'VISION' ...
** using staged installation
** libs
g++ -std=gnu++17  -I"C:/Users/NILOUF~1/AppData/Local/Programs/R/R-43~1.0/include" -DNDEBUG -DROUT -lgopm -I'C:/Users/NiloufarKhojandi/AppData/Local/Programs/R/R-4.3.0/library/Rcpp/include'   -I"c:/rtools43/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c Geary.cpp -o Geary.o
/bin/sh: line 1: g++: command not found
make: *** [C:/Users/NILOUF~1/AppData/Local/Programs/R/R-43~1.0/etc/x64/Makeconf:272: Geary.o] Error 127
ERROR: compilation failed for package 'VISION'
* removing 'C:/Users/NiloufarKhojandi/AppData/Local/Programs/R/R-4.3.0/library/VISION'
Warning messages:
1: In i.p(...) : installation of package ‘httpuv’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘C:/Users/NILOUF~1/AppData/Local/Temp/RtmpGm7dIC/filea77c69b64056/VISION_3.0.1.tar.gz’ had non-zero exit status

**Comment by Andre75952** [comment]
I met this problem too.Installing this package after updating my R to 4.3.0,the same error came up.During I searching for help,I noticed the sentence "g++ :command not found".It seems that this error caused by lower-version Rtools.After I installing new version,the error was done.
